### ISSUE TITLE
Gather data for site

### ISSUE THREAD

**Issue by designelixir** [elliotwhitehead/SummitPlan#4]
gather the overall elevation, mountain rank, coordinates, round trip distance

**Comment by coloradical** [comment]
https://docs.google.com/spreadsheets/d/18B7H4d5ZFTWdJm3ck--mUAstRod4AO45fwLjW-E2FCY/edit?usp=sharing

**Comment by designelixir** [comment]
https://docs.google.com/spreadsheets/d/1tTE5uuDRdEJqeo7bOgLrEv815MEv4b6o4YL0Lt29VtQ/edit?usp=sharing
