### ISSUE TITLE
PRESENTATION!

### ISSUE THREAD

**Issue by designelixir** [elliotwhitehead/SummitPlan#5]
Presentation for our recitation 7.

**Comment by designelixir** [comment]
https://docs.google.com/presentation/d/1koCCcs0loYGnI96Ydw1spktn5MgEBLOBT3cUZYbKfCY/edit?usp=sharing

Here is the link to our slides, which I'm currently working on!

**Comment by elliotwhitehead** [comment]
Great! I'll send the video over soon!

**Comment by elliotwhitehead** [comment]
Thanks for all your help on this everyone!  I'm sorry again for that slip on the video 🙈
