### ISSUE TITLE
Use Cases

### ISSUE THREAD

**Issue by designelixir** [elliotwhitehead/SummitPlan#6]

**Comment by designelixir** [comment]
![generic use case](https://user-images.githubusercontent.com/32202291/31749091-f9b251da-b434-11e7-9e5c-fbaa14d0c963.png)
![summitplan multiple user use case](https://user-images.githubusercontent.com/32202291/31749093-fb0171b0-b434-11e7-9e76-1e1baba47390.png)
![basic use case](https://user-images.githubusercontent.com/32202291/31749094-fc57e094-b434-11e7-9635-e968c1e93dc7.png)

**Comment by elliotwhitehead** [comment]
@coloradical These are awesome. Would you mind checking them into the repo, in a new directory called 'use cases', inside the 'docs' directory? Let me know if you have any questions!

**Comment by designelixir** [comment]
Let me get back to you hahah, I have no idea how to do this and I still need to get my computer back to its normal state - I reset it and haven't downloaded everything I had before

**Comment by elliotwhitehead** [comment]
Okay no worries! I'm happy to help, just let me know when you're free and I can jump on a call!
